### ISSUE TITLE
Convert to function

### ISSUE THREAD

**Issue by kbrannan** [Creutzx/ElevMap#3]
Take ElevMap script and convert it to a function.

**Comment by Creutzx** [comment]
I created a new repository for this, the code is here:

https://github.com/Creutzx/WatershedMap/invitations

After you accept, I will open an issue if I haven't finished debugging yet.

**Comment by Creutzx** [comment]
Elevation map script is now a function.

The other repository was created in an attempt to get all the maps with a single script, so no need to check it out if this was all you were wanting.

**Comment by kbrannan** [comment]
Looks good, take the variables (the "str_" varuables) and set the as inputs to the function. Then use it is a script to check it out

**Comment by Creutzx** [comment]
I'm not sure what you mean here, can you point me to an example?

**Comment by kbrannan** [comment]
Currently you have the function variables in the function (see below) and the user cannot change them without accessing the function code directly.

```
def ElevMap():
    import arcpy
    str_dir_main = r"\\DEQHQ1\TMDL\TMDL_WR\MidCoast\GIS\Figures\Upper_Yaquina_Maps"
    str_mxd_blank = r"Upper_Yaquina_TMDL_Blank_ME.mxd"
    str_df_cur = r"Layers"
    str_lyr_cur = r"UY_Elev.lyr"
    str_mxd_save = r"Upper_Yaquina_TMDL_UY_Elev.mxd"
```

Move the variables to be within the parentheses of the function like this:
```
def ElevMap(str_dir_main , str_mxd_blank, str_df_cur,  str_lyr_cur, str_mxd_save ):
    import arcpy
 
```


Then the user of the function can assign values to the variables when they use it in their code.
Make the changes and then try it out in a script.

**Comment by Creutzx** [comment]
This works, changes made.

**Comment by kbrannan** [comment]
Great!
